# -*- coding: utf-8 -*-
"""translator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SxzKeBKpnbpDgOvtpABlxACPWs5UGH8w
"""

# pip = python install packages

!pip install googletrans==4.0.0-rc1

from googletrans import Translator, LANGUAGES
translator = Translator()
language_options = LANGUAGES.items()

language_code = []
language_name = []

for code, name in language_options:
  language_code.append(code)
  language_name.append(name)

def errors():
  print("unknown language")
  print(f"language codes: {language_code}")
  print(f"language names: {language_name}")

try:
  translating_from = input("Enter the language you want to translate from: ")
  word = input("Enter the word you want to translate: ")
  translating_to = input("Enter the language you want to translate to: ")

  if (translating_from in language_code or translating_from in language_name) and \
     (translating_to in language_code or translating_to in language_name):
    translation = translator.translate(word, src=translating_from, dest=translating_to)
    print(translation.text.capitalize())
  else:
    errors()
except Exception as e:
  print("something went wrong:")
  print(e)
  errors()